---
- name: Creating DIUN data folder
  become: true
  block:
    - name: Checking data folder exists
      ansible.builtin.stat:
        path: '{{ diun_data_folder }}'
      register: diun_data_folder_stat

    - name: Creating data folder
      ansible.builtin.file:
        path: '{{ diun_data_folder }}'
        state: directory
        mode: 0700
        owner: 101000
        group: 101000
      when: not (diun_data_folder_stat | community.general.json_query('stat.exists'))

- name: Ensuring DIUN network exists
  community.docker.docker_network:
    name: diun
    driver: bridge
    internal: true
    state: present

- name: Create socket proxy container
  community.docker.docker_container:
    name: diun-socket-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy
    keep_volumes: false
    userns_mode: host
    privileged: true
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - name: diun
        aliases:
          - socket-proxy
    env:
      CONTAINERS: '1'
      IMAGES: '1'

- name: Ensuring DIUN outside network exists
  community.docker.docker_network:
    name: diun-outside
    driver: bridge
    internal: false
    state: present

- name: Create DIUN container
  community.docker.docker_container:
    name: diun
    image: ghcr.io/crazy-max/diun
    keep_volumes: false
    restart_policy: unless-stopped
    env:
      TZ: Europe/Rome
      DIUN_WATCH_WORKERS: 2
      DIUN_WATCH_SCHEDULE: 0 20 * * *
      DIUN_PROVIDERS_DOCKER: 'true'
      DIUN_PROVIDERS_DOCKER_ENDPOINT: tcp://socket-proxy:2375
      DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: 'true'
      DIUN_NOTIF_TELEGRAM_TOKEN: '{{ diun_telegram_bot_token }}'
      DIUN_NOTIF_TELEGRAM_CHATIDS: '{{ diun_telegram_chat_ids }}'
    networks:
      - name: diun
      - name: diun-outside
    mounts:
      - type: bind
        source: '{{ diun_data_folder }}'
        target: /var/www/html
