---
- name: Ensuring config folder exists
  ansible.builtin.file:
    path: '{{ nextcloud_config_folder }}'
    state: directory
    mode: 0755

- name: Ensuring data folder exists
  ansible.builtin.file:
    path: '{{ nextcloud_data_folder }}'
    state: directory
    mode: 0755

- name: Creating Nextcloud volume folders
  become: true
  block:
    - name: Creating database folder
      ansible.builtin.file:
        path: '{{ (nextcloud_data_folder, "data") | path_join }}'
        state: directory
        mode: 0700
        owner: 100000999
        group: 100000999
    
    - name: Creating application folders
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: 0700
        owner: 100001000
        group: 100001000
      with_items:
        - '{{ (nextcloud_data_folder, "app-config") | path_join }}'
        - '{{ (nextcloud_data_folder, "app-data") | path_join }}'

- name: Copy Server Transport for Traefik
  ansible.builtin.copy:
    src: nextcloud_transport.yml
    dest: '{{ traefik_dynamic_config_folder }}'
    mode: 0444

- name: Templating Nextcloud's compose
  ansible.builtin.template:
    src: compose.yml
    dest: '{{ (nextcloud_config_folder, "compose.yml") | path_join }}'
    mode: 0700

- name: Start Nextcloud
  community.docker.docker_compose_v2:
    project_src: '{{ nextcloud_config_folder }}'
  notify:
    - Add internal networks in firewalld

- name: Create DNS Records for cloud.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: cloud

- name: Create DNS Records for office.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: office
