---
- name: Ensuring data folder exists
  ansible.builtin.file:
    path: '{{ nextcloud_data_folder }}'
    state: directory
    mode: 0755

- name: Creating Nextcloud volume folders
  become: true
  block:
    - name: Checking database folder exists
      ansible.builtin.stat:
        path: '{{ (nextcloud_data_folder, "data") | path_join }}'
      register: nextcloud_database_folder

    - name: Creating database folder
      ansible.builtin.file:
        path: '{{ (nextcloud_data_folder, "data") | path_join }}'
        state: directory
        mode: 0700
        owner: 101000
        group: 101000
      when: not (nextcloud_database_folder.stat.exists)
    
    - name: Checking application folder exists
      ansible.builtin.stat:
        path: '{{ (nextcloud_data_folder, "app") | path_join }}'
      register: nextcloud_application_folder

    - name: Creating application folder
      ansible.builtin.file:
        path: '{{ (nextcloud_data_folder, "app") | path_join }}'
        state: directory
        mode: 0700
        owner: 101000
        group: 101000
      when: not (nextcloud_application_folder.stat.exists)

- name: Ensuring Nextcloud network exists
  community.docker.docker_network:
    name: nextcloud
    driver: bridge
    internal: true
    state: present

- name: Create Redis container
  community.docker.docker_container:
    name: nextcloud-redis
    image: redis:alpine
    command: 'redis-server --requirepass {{ nextcloud_redis_password }}'
    restart_policy: unless-stopped
    keep_volumes: false
    networks:
      - name: nextcloud
        aliases:
          - redis

- name: Create MariaDB container
  community.docker.docker_container:
    name: nextcloud-database
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart_policy: unless-stopped
    keep_volumes: false
    env:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: '{{ nextcloud_database_password }}'
    mounts:
      - type: bind
        source: '{{ (nextcloud_data_folder, "data") | path_join }}'
        target: /var/lib/mysql
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - name: nextcloud
        aliases:
          - database

- name: Ensuring Nextcloud Outside network exists
  community.docker.docker_network:
    name: nextcloud-outside
    driver: bridge
    internal: false
    state: present

#TODO: Run sed -i '/0 => '"'"'cloud.magisystem.xyz'"'"'/a \ \ \ \ 1 => '"'"'cloud'"'"'' config/config.php with blockinfile
#TODO: change trusted_proxies with blockinfile
- name: Create Nextcloud container
  community.docker.docker_container:
    name: nextcloud
    image: nextcloud
    keep_volumes: false
    restart_policy: unless-stopped
    env:
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: '{{ nextcloud_database_password }}'
      MYSQL_HOST: database
      REDIS_HOST: redis
      #TRUSTED_PROXIES=192.168.0.0/24
      #APACHE_DISABLE_REWRITE_IP=1
      #OVERWRITEHOST=cloud.magisystem.xyz
      OVERWRITEPROTOCOL: https
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.magisystem.xyz
      TRUSTED_PROXIES: '{{ reverse_proxy_network_subnet }}'
      REDIS_HOST_PASSWORD: '{{ nextcloud_redis_password }}'
      SMTP_HOST: '{{ mail_server["host"] }}'
      SMTP_SECURE: '{{ mail_server["use_ssl"] | bool | ternary("ssl", mail_server["use_tls"] | bool | ternary("tls", "")) }}'
      SMTP_PORT: '{{ mail_server["port"] }}'
      SMTP_AUTHTYPE: '{{ mail_server["username"] | bool | ternary("LOGIN", "PLAIN") }}'
      SMTP_NAME: '{{ mail_server["username"] }}'
      SMTP_PASSWORD: '{{ mail_server["password"] }}'
      MAIL_FROM_ADDRESS: '{{ nextcloud_mail_from | default("") }}'
    networks:
      - name: nextcloud
        aliases:
          - cloud
      - name: nextcloud-outside
      - name: '{{ reverse_proxy_network }}'
    mounts:
      - type: bind
        source: '{{ (nextcloud_data_folder, "app") | path_join }}'
        target: /var/www/html
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    labels:
      com.centurylinklabs.watchtower.depends-on: nextcloud-redis,nextcloud-database
      traefik.enable: 'true'
      traefik.http.routers.nextcloud.entryPoints: https
      traefik.http.routers.nextcloud.rule: Host(`cloud.magisystem.xyz`)
      traefik.http.routers.nextcloud.middlewares: nextcloud-header,nextcloud-redirect
      traefik.http.middlewares.nextcloud-header.headers.stsSeconds: '15552000'
      traefik.http.middlewares.nextcloud-redirect.redirectregex.regex: /.well-known/(card|cal)dav
      traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement: /remote.php/dav/
      traefik.http.middlewares.nextcloud-redirect.redirectregex.permanent: 'true'
      traefik.http.services.nextcloud.loadbalancer.server.port: '80'

- name: Create Nextcloud cronjob container
  community.docker.docker_container:
    name: nextcloud-cronjobs
    image: nextcloud
    entrypoint: /cron.sh
    keep_volumes: false
    restart_policy: unless-stopped
    networks:
      - name: nextcloud
    mounts:
      - type: bind
        source: '{{ (nextcloud_data_folder, "app") | path_join }}'
        target: /var/www/html
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    labels:
      com.centurylinklabs.watchtower.depends-on: nextcloud
