---
- name: Ensuring traefik config folder exists
  ansible.builtin.file:
    path: '{{ traefik_config_folder }}'
    state: directory
    mode: 0755

- name: Ensuring traefik dynamic config folder exists
  ansible.builtin.file:
    path: '{{ traefik_config_folder }}/configs'
    state: directory
    mode: 0755

#TODO: The default network might need to be created here, as well as the "outside" bridge network

- name: Template Traefik's Static Config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: '{{ traefik_config_folder }}/traefik.yml'
    mode: 0400
  register: edge_containers_traefik_static_config

- name: Create socket proxy container
  community.docker.docker_container:
    name: traefik-socket-proxy
    image: tecnativa/docker-socket-proxy
    pull: True
    keep_volumes: False
    userns_mode: host
    privileged: True
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: True
    networks:
      - name: traefik
        aliases:
          - 'socket-proxy'
    env:
      CONTAINERS: 1

- name: Create reverse proxy container
  community.docker.docker_container:
    name: traefik
    image: traefik
    pull: True
    keep_volumes: False
    restart_policy: unless-stopped
    restart: '{{ edge_containers_traefik_static_config is changed }}'
    mounts:
      - type: bind
        source: '{{ traefik_config_folder }}/traefik.yml'
        target: /etc/traefik/traefik.yml
        read_only: True
      - type: bind
        source: '{{ traefik_config_folder }}/configs'
        target: /etc/traefik/configs
        read_only: True
    networks:
      - name: traefik
      - name: '{{ reverse_proxy_network }}'
    published_ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8081:8081'
      - '127.0.0.1:8082:8082'

#  reverse-proxy:
#    networks:
#      - {{ reverse_proxy_network }}
#      - default
#      - outside
