---
- name: Ensuring traefik config folder exists
  ansible.builtin.file:
    path: '{{ traefik_config_folder }}'
    state: directory
    mode: 0755

- name: Ensuring traefik dynamic config folder exists
  ansible.builtin.file:
    path: '{{ traefik_config_folder }}/configs'
    state: directory
    mode: 0755

- name: Create traefik network
  community.docker.docker_network:
    name: traefik
    driver: bridge
    internal: true
    state: present

- name: Create traefik-outside network
  community.docker.docker_network:
    name: traefik-outside
    driver: bridge
    internal: false
    state: present

- name: Template Traefik's Static Config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: '{{ traefik_config_folder }}/traefik.yml'
    mode: 0400
  register: edge_containers_traefik_static_config

- name: Copy Traefik's dynamic file configs
  ansible.builtin.copy:
    src: configs/
    dest: '{{ traefik_config_folder }}/configs'
    mode: 0600

- name: Create socket proxy container
  community.docker.docker_container:
    name: traefik-socket-proxy
    image: tecnativa/docker-socket-proxy
    pull: true
    keep_volumes: false
    userns_mode: host
    privileged: true
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - name: traefik
        aliases:
          - 'socket-proxy'
    env:
      CONTAINERS: '1'

- name: Create reverse proxy container
  community.docker.docker_container:
    name: traefik
    image: traefik
    pull: true
    keep_volumes: false
    restart_policy: unless-stopped
    restart: '{{ edge_containers_traefik_static_config is changed }}'
    mounts:
      - type: bind
        source: '{{ traefik_config_folder }}/traefik.yml'
        target: /etc/traefik/traefik.yml
        read_only: true
      - type: bind
        source: '{{ traefik_config_folder }}/configs'
        target: /etc/traefik/configs
        read_only: true
    networks:
      - name: traefik
      - name: traefik-outside
      - name: '{{ reverse_proxy_network }}'
    published_ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8081:8081'
      - '127.0.0.1:8082:8082'
