---
- name: Ensuring config folder exists
  ansible.builtin.file:
    path: '{{ container_config_folder }}'
    state: directory
    mode: 0755

- name: Ensuring volumes folder exists
  ansible.builtin.stat:
    path: '{{ container_volumes_folder }}'
  register: edge_setup_volumes
  failed_when: not edge_setup_volumes.stat.exists

- name: Create services network
  community.docker.docker_network:
    name: reverse-proxy
    driver: bridge
    internal: true
    ipam_config:
      - gateway: '{{ reverse_proxy_network_gateway }}'
        subnet: '{{ reverse_proxy_network_subnet }}'
    state: present
  notify:
    - Add internal networks in firewalld
