---
- name: Ensuring container config folder exists
  ansible.builtin.file:
    path: '{{ grocy_config_folder }}'
    state: directory
    mode: 0755

- name: Ensuring container data folder exists
  become: true
  ansible.builtin.file:
    path: '{{ grocy_data_folder }}'
    state: directory
    owner: 100001000
    group: 100001000
    mode: 0755

- name: Templating compose file
  ansible.builtin.template:
    src: compose.yml
    dest: '{{ (grocy_config_folder | mandatory, "compose.yml") | path_join }}'
    mode: 0644

- name: Starting Grocy
  community.docker.docker_compose_v2:
    project_src: '{{ grocy_config_folder }}'

- name: Create DNS Records for grocy.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: grocy
