---
- name: Ensuring container config folder exists
  ansible.builtin.file:
    path: '{{ grocy_config_folder }}'
    state: directory
    mode: 0744

- name: Templating compose file
  ansible.builtin.template:
    src: compose.yml
    dest: '{{ (grocy_config_folder | mandatory, "compose.yml") | path_join }}'
    mode: 0544

- name: Starting Grocy
  community.docker.docker_compose_v2:
    project_src: '{{ grocy_config_folder }}'

- name: Create DNS Records for grocy.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: grocy
