---
- name: Ensuring data folder exists
  become: true
  ansible.builtin.file:
    path: '{{ mailserver_data_folder }}'
    state: directory
    mode: 0755

- name: Moving mailserver configuration
  become: true
  block:
    - name: Templating mailserver env file
      vars:
        mailserver_ldap:
          search_base_dn: ''
          bind_dn: ''
          bind_pw: ''
      ansible.builtin.template:
        src: mailserver.env.j2
        dest: '{{ mailserver_config_file }}'
        mode: 0400
        owner: 100000
        group: 100000

    - name: Ensuring mail folder exists
      become: true
      ansible.builtin.file:
        path: '{{ (mailserver_data_folder, "mail") | path_join }}'
        state: directory
        mode: 0700
        owner: 101000
        group: 101000

    - name: Ensuring mail-state folder exists
      ansible.builtin.file:
        path: '{{ (mailserver_data_folder, "mail-state") | path_join }}'
        state: directory
        mode: 0700
        owner: 101000
        group: 101000

    - name: Ensuring config folder exists
      ansible.builtin.file:
        path: '{{ (mailserver_data_folder, "config") | path_join }}'
        state: directory
        mode: 0755
        owner: 101000
        group: 101000

- name: Ensuring mail network exists
  community.docker.docker_network:
    name: mail
    driver: bridge
    internal: true
    state: present
  register: mailserver_network

- name: Templating mailserver's custom postfix conf file
  become: true
  vars:
    mailserver_network_subnet: '{{ mailserver_network | community.general.json_query("network.IPAM.Config[0].Subnet") }}'
  ansible.builtin.template:
    src: postfix-mynetworks.cf.j2
    dest: '{{ (mailserver_data_folder, "config", "postfix-main.cf") | path_join }}'
    mode: 0444 owner: 101000 group: 101000

- name: Ensuring mailserver-outside network exists
  community.docker.docker_network:
    name: mailserver-outside
    driver: bridge
    internal: false
    state: present

#TODO: Restart in case config changed
- name: Create mailserver container
  community.docker.docker_container:
    name: mailserver
    image: ghcr.io/docker-mailserver/docker-mailserver:edge
    keep_volumes: false
    restart_policy: unless-stopped
    hostname: '{{ mailserver_hostname }}'
    domainname: '{{ mailserver_domainname }}'
    env_file: '{{ mailserver_config_file }}'
    stop_timeout: 1m
    capabilities:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    mounts:
      - type: bind
        source: '{{ (mailserver_data_folder, "mail") | path_join }}'
        target: /var/mail
      - type: bind
        source: '{{ (mailserver_data_folder, "mail-state") | path_join }}'
        target: /var/mail-state
      - type: bind
        source: '{{ (mailserver_data_folder, "config") | path_join }}'
        target: /tmp/docker-mailserver
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    networks:
      - name: mail
        aliases:
          - mailserver
      - name: mailserver-outside
    published_ports:
      - '25:25'   # SMTP  (explicit TLS => STARTTLS)
#      - '143:143' # IMAP4 (explicit TLS => STARTTLS)
      - '465:465' # ESMTP (implicit TLS)
      - '587:587' # ESMTP (explicit TLS => STARTTLS)
#      - '993:993' # IMAP4 (implicit TLS)
#      - '110:110' # POP3
#      - '995:995' # POP3 with TLS
