---
- name: Setting up the Magisystem
  hosts: edge
  gather_facts: false
  roles:
    - role: state_gathering
    - role: edge/install
      when: not (setup_completed | bool)

- name: Managing containers on the Magisystem
  hosts: edge
  become: True
  vars:
    container-volumes-folder: '/var/{{ container-volumes-folder }}'
  roles:
    - role: edge/containers
