---
- name: Setting up the Magisystem
  hosts: edge
  gather_facts: false
  roles:
    - role: state_gathering
    - role: edge/install
      when: not (setup_completed | bool)

- name: Managing containers on the Magisystem
  hosts: edge
  vars:
    container_volumes_folder: '/var/container-volumes'
    container_config_folder: '{{ ansible_facts.env.HOME }}/config'
  roles:
    - role: edge/containers/setup
    - role: edge/containers/traefik
