---
- name: Setting up the Magisystem
  hosts: edge
  gather_facts: false
  roles:
    - role: state_gathering
    - role: edge/install
      when: not (setup_completed | bool)

- name: Managing containers on the Magisystem
  hosts: edge
  roles:
    - role: edge/containers
