---
- name: Installing OS to the Magisystem
  hosts: hetzner
  gather_facts: false
  pre_tasks:
    # Check for connection, fail if accessible through custom port and username, meaning that the OS is already installed
    - name: Checking connection
      ansible.builtin.wait_for_connection:
        timeout: 10
      failed_when
      vars:
        ansible_user: '{{hetzner_install_ansible_user}}'
        ansible_port: '{{hetzner_install_ansible_port}}'
  roles:
    - role: hetzner/install

- name: Managing containers on the Magisystem
  hosts: edge
  vars:
    container_volumes_folder: '/var/container-volumes'
    container_config_folder: '{{ ansible_facts.env.HOME }}/config'
# pre_tasks:
#   # Check if Reboot happened
#   - name: SSH Check
#     ansible.builtin.wait_for_connection: {}
  roles:
    - role: edge/setup
    - role: edge/traefik
