---
- name: Gather the state of the Magisystem
  hosts: edge
  gather_facts: false
  roles:
    - state_gathering

- name: Setting up the Magisystem
  hosts: edge
  gather_facts: false
  pre_tasks:
  roles:
    - role: edge/install
      when: host_state | int >= possible_host_states.not_installed
    - role: edge/setup
      when: host_state | int >= possible_host_states.just_installed
    - role: edge/containers
      when: host_state | int >= possible_host_states.ready
