---
- name: Gather the state of the Magisystem
  hosts: edge
  gather_facts: false
  roles:
    - state_gathering

- name: Setting up the Magisystem
  hosts: edge
  gather_facts: false
  pre_tasks:
    # Placeholder for automatic OS installation
    - name: Install OS
      ansible.builtin.fail:
        msg: Install OpenSuse
      when: host_state | int >= possible_host_states.not_installed
  roles:
    - role: edge/setup
      when: host_state | int >= possible_host_states.just_installed
    - role: edge/containers
      when: host_state | int >= possible_host_states.ready
