- hosts: edge
  gather_facts: False
  tasks:
    - block:
        - ansible.builtin.fail:
            msg: bruh
      always:
        - ansible.builtin.debug:
            msg: from always
    - ansible.builtin.debug:
        msg: from second task
