---
services:
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    environment:
      ND_SESSIONTIMEOUT: 24h
      ND_TRANSCODINGCACHESIZE: 5 GiB
      #ND_ENABLETRANSCODINGCONFIG: 'true'
      ND_ENABLESHARING: 'true'
      ND_REVERSEPROXYWHITELIST: '{{ reverse_proxy_network_subnet }}'
      ND_REVERSEPROXYUSERHEADER: X-authentik-username
      ND_SUBSONICARTISTPARTICIPATIONS: 'true'
      ND_LASTFM_ENABLED: 'true'
      ND_LASTFM_APIKEY: '{{ navidrome_lastfm_apikey }}'
      ND_LASTFM_SECRET: '{{ navidrome_lastfm_secret }}'
      ND_SPOTIFY_ID: '{{ navidrome_spotify_clientid }}'
      ND_SPOTIFY_SECRET: '{{ navidrome_spotify_secret }}'
      ND_LOGLEVEL: debug
    networks:
      - outside
      - reverse-proxy-network
    volumes:
      - '{{ navidrome_data_folder }}:/data'
      - '{{ navidrome_music_folder }}:/music:ro'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.navidrome.entryPoints: https
      traefik.http.routers.navidrome.rule: Host(`music.magisystem.xyz`)
      traefik.http.routers.navidrome.middlewares: navidrome-auth
      traefik.http.routers.navidrome.service: navidrome
      traefik.http.routers.navidrome-api-no-auth.entryPoints: https
      traefik.http.routers.navidrome-api-no-auth.rule: Host(`music.magisystem.xyz`) && PathPrefix(`/rest`, `/share`)
      traefik.http.routers.navidrome-api-no-auth.service: navidrome
      traefik.http.routers.navidrome-auth.entryPoints: https
      traefik.http.routers.navidrome-auth.rule: Host(`music.magisystem.xyz`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.navidrome-auth.service: 'authentik@{{ (authentik_role == "server") | ternary("docker", "file") }}'
      traefik.http.middlewares.navidrome-auth.forwardauth.address: https://music.magisystem.xyz/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.navidrome-auth.forwardauth.trustForwardHeader: 'true'
      traefik.http.middlewares.navidrome-auth.forwardauth.authResponseHeaders: X-authentik-username #,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
      traefik.http.services.navidrome.loadbalancer.server.port: '4533'

networks:
  outside:
    internal: false
  reverse-proxy-network:
    name: '{{ reverse_proxy_network }}'
    external: true
