---
reverse_proxy_network: '{{ undef(hint="Reverse Proxy Docker network") }}'
traefik_config_folder: '{{ (container_config_folder | mandatory, "traefik") | path_join }}'
certificate_email: '{{ undef(hint="Email to send to Let''s Encrypt") }}'
