---
reverse_proxy_network: '{{ undef(hint="Reverse Proxy Docker network") }}'
bitwarden_data_folder: '{{ (container_volumes_folder | mandatory, "bwarden") | path_join }}'
bitwarden_database_password: '{{ undef(hint="Bitwarden Database''s password") }}'
bitwarden_mail_from: '{{ undef(hint="Email address bitwarden will send as, should have a correct @domain") }}'
bitwarden_ldap_config_file: '{{ (container_config_folder | mandatory, "vaultwarden_ldap.toml") | path_join }}'
