---
bitwarden_data_folder: '{{ (container_volumes_folder | mandatory, "bwarden") | path_join }}'
bitwarden_database_password: '{{ undef(hint="Bitwarden Database''s password") }}'
bitwarden_admin_password: '{{ undef(hint="Bitwarden''s admin password") }}'
bitwarden_mail_from: '{{ undef(hint="Email address bitwarden will send as, should have a correct @domain") }}'
bitwarden_config_folder: '{{ (container_config_folder | mandatory, "bwarden") | path_join }}'
