---
- name: Ensuring config folder exists
  ansible.builtin.file:
    path: '{{ authentik_config_folder }}'
    state: directory
    mode: 0755

- name: Ensuring data folder exists
  ansible.builtin.file:
    path: '{{ authentik_data_folder }}'
    state: directory
    mode: 0755

- name: Creating authentik volume folders
  become: true
  block:
    - name: Creating database folder
      ansible.builtin.file:
        path: '{{ (authentik_data_folder, "data") | path_join }}'
        state: directory
        mode: 0700
        owner: 100000070
        group: 100000070
    
    - name: Ensuring worker media folder exists
      ansible.builtin.file:
        path: '{{ (authentik_data_folder, "media") | path_join }}'
        state: directory
        mode: 0700
        owner: 100001000
        group: 100001000
    
    - name: Ensuring custom templates folder exists
      ansible.builtin.file:
        path: '{{ (authentik_data_folder, "custom-templates") | path_join }}'
        state: directory
        mode: 0755
        owner: 100001000
        group: 100001000
    
    - name: Ensuring certs folder exists
      ansible.builtin.file:
        path: '{{ (authentik_data_folder, "certs") | path_join }}'
        state: directory
        mode: 0700
        owner: 100001000
        group: 100001000

- name: Templating authentik's Compose
  ansible.builtin.template:
    src: docker-compose.yml
    dest: '{{ (authentik_config_folder, "compose.yml") | path_join }}'
    mode: 0600

- name: Starting authentik
  community.docker.docker_compose_v2:
    project_src: '{{ authentik_config_folder }}'
  notify:
    - Add internal networks in firewalld

- name: Create DNS Records for auth.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: auth
