---
- name: 'Create DNS Records for {{ hetzner_dns_record_prefix }}.magisystem.xyz'
  connection: local
  delegate_to: localhost
  run_once: true
  community.dns.hetzner_dns_record_sets:
    hetzner_token: '{{ hetzner_dns_api_token }}'
    zone_name: magisystem.xyz
    bulk_operation_threshold: 3
    record_sets:
      - prefix: '{{ hetzner_dns_record_prefix }}'
        type: CAA
        value: 128 issue "letsencrypt.org"
      - prefix: '{{ hetzner_dns_record_prefix }}'
        type: A
        value: '{{ hetzner_dns_record_ipv4 }}'
      #TODO: Enable Docker's IPv6 support
      #- prefix: '{{ hetzner_dns_record_prefix }}'
      #  type: AAAA
      #  value: '{{ hetzner_dns_record_ipv6 }}'
