---
- name: 'Create DNS Records for {{ hetzner_dns_record_prefix }}.magisystem.xyz'
  connection: local
  delegate_to: localhost
  run_once: true
  community.dns.hetzner_dns_record_set:
    hetzner_token: '{{ hetzner_dns_api_token }}'
    zone_name: magisystem.xyz
    state: present
    prefix: '{{ hetzner_dns_record_prefix }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  when: item.value != omit
  loop:
    - type: CAA
      value: 128 issue "letsencrypt.org"
    - type: A
      value: '{{ hetzner_dns_record_ipv4 | default(omit) }}'
    #TODO: Enable Docker's IPv6 support
    #- type: AAAA
    #  value: '{{ hetzner_dns_record_ipv6 | default(omit) }}'
