---
- name: Ensuring Watchtower config folder exists
  ansible.builtin.file:
    path: '{{ watchtower_config_folder }}'
    state: directory
    mode: 0755

- name: Template Watchtower's Compose file
  ansible.builtin.template:
    src: compose.yml
    dest: '{{ (watchtower_config_folder, "compose.yaml") | path_join }}'
    mode: 0444

- name: Start Watchtower
  community.docker.docker_compose_v2:
    project_src: '{{ watchtower_config_folder }}'
