---
# TODO: Upload ssh key and put machine in recovery with hetzner hcloud
# Change port and user to hetzner recovery's defaults
- name: Changing to default ssh parameters
  ansible.builtin.set_fact:
    edge_install_ansible_port: '{{ ansible_port }}'
    edge_install_ansible_user: '{{ ansible_user }}'
    ansible_port: 22
    ansible_user: root

# WARNING: THIS IS STILL UNTESTED, Everything else in this role is known to work but this task
# TODO: Check whether apt-get is idempotent and returns 0 if package is already installed
- name: Installing Python
  ansible.builtin.raw: 'apt-get -y -q update && apt-get -y -q install python3'
  register: edge_install_install_python_result
  changed_when: edge_install_install_python_result.rc == 0

# Gather facts to choose installation drive
- name: Gathering facts
  ansible.builtin.setup: {}

# Choose the first drive that isn't mounted
- name: Choosing installation drive
  ansible.builtin.set_fact:
    edge_install_installation_drive: '{{ item }}'
  loop: '{{ non_removable_devices }}'
  # Set Fact runs only if the variable has not been defined and if the list of indices returned by index_of is empty
  when: >
    edge_install_installation_drive is undefined and
    (mounted_partitions | ansible.utils.index_of('search', item, fail_on_missing=False, wantlist=True) | length) == 0
  vars:
    mounted_partitions: '{{ ansible_facts.mounts | map(attribute="device") | unique }}'
    non_removable_devices: '{{ ansible_facts.devices | dict2items | rejectattr("value.removable", "truthy", convert_bool=True) | map(attribute="key") | sort }}'

- name: Fail if we couldn't find an installation drive
  ansible.builtin.fail:
    msg: 'Couldn''t find an installation drive among {{ ansible_facts.devices.keys() | list }}'
  when: edge_install_installation_drive is undefined

- name: Stop before installation
  ansible.builtin.pause:
    echo: False
    prompt: 'MicroOS is about to be installed on {{ inventory_hostname }}''s remote device /dev/{{ edge_install_installation_drive }}'
    seconds: 10

- block:
    - name: Sending installation script
      ansible.builtin.copy:
        src: install_ignition.sh
        dest: ./install_ignition.sh
        mode: 0544
    - name: Run installation script
      ansible.builtin.command: './install_ignition.sh /dev/{{ edge_install_installation_drive }}'
      register: edge_install_script_result
      failed_when: edge_install_script_result.rc != 0
      changed_when: edge_install_script_result.rc == 0
  always:
    - name: Show command result
      ansible.builtin.debug:
        msg: '{{ edge_install_script_result is succeeded | ternary(edge_install_script_result.stdout_lines, edge_install_script_result.stderr_lines) }}'
      when: edge_install_script_result is defined
    # Remove script if sent
    - name: Removing temporary file
      ansible.builtin.file:
        path: ./install_ignition.sh
        state: absent

# Update facts with new partition
- name: Updating facts
  ansible.builtin.setup:
    gather_subset:
      - hardware

# The partition should have been created by install_ignition.sh
- name: Choose config partition
  ansible.builtin.set_fact:
    edge_install_ignition_partition: '{{ partitions[(partitions | length) - 1] }}'
  vars:
    partitions: '{{ ansible_facts.devices[edge_install_installation_drive].partitions.keys() | sort }}'

- name: Formatting the config partition
  community.general.filesystem:
    dev: '/dev/{{ edge_install_ignition_partition }}'
    fstype: ext4
    opts: -L ignition
    state: present

- block:
    # Mount config partition
    - name: Mounting the last partition
      ansible.posix.mount:
        boot: False
        src: '/dev/{{ edge_install_ignition_partition }}'
        fstype: ext4
        path: /mnt/ignition
        state: mounted

    # Locally generate Ignition config from Butane template
    - name: Generate Ignition config
      delegate_to: localhost
      connection: local
      block:
        # Create temporary file where to put the templated config
        - name: Creating temporary file to host templated config
          ansible.builtin.tempfile:
            suffix: '.bu'
          register: edge_install_butane_config
        - name: Templating Butane config
          ansible.builtin.template:
            src: ignition_file.bu.j2
            dest: '{{ edge_install_butane_config.path }}'
        # Transpile Butane config to get Ignition json
        - name: Transpiling Butane config
          containers.podman.podman_container:
            interactive: True
            detach: False
            rm: True
            image: quay.io/coreos/butane:release
            volume:
              - '{{ edge_install_butane_config.path }}:/config.bu'
            command: '--strict /config.bu'
            name: butane
          register: edge_install_ignition_config
      always:
        # Remove temporary file if created
        - name: Removing temporary files
          ansible.builtin.file:
            path: '{{ edge_install_butane_config.path }}'
            state: absent
          when: edge_install_butane_config is defined

    - name: Create ignition folder
      ansible.builtin.file:
        path: /mnt/ignition/ignition
        state: directory
        mode: 0755

    # Write the ignition config in /ignition/config.ign
    - name: Writing ignition config
      ansible.builtin.copy:
        content: '{{ edge_install_ignition_config.stdout | string }}'
        dest: /mnt/ignition/ignition/config.ign
        mode: 0644

    - name: Create combustion folder
      ansible.builtin.file:
        path: /mnt/ignition/combustion
        state: directory
        mode: 0755

    - name: Add script file
      ansible.builtin.template:
        src: combustion_script.j2
        dest: /mnt/ignition/combustion/script
        mode: 0744
  always:
    # Unmount the config partition if mounted
    - name: Unmounting the last partition
      ansible.posix.mount:
        boot: False
        path: /mnt/ignition
        state: absent

# Reboot to disk (reboots deactivate hetzner's recovery environment)
# We have a very short timeout and ignore errors because sshd should be listening to another port
- name: Rebooting to disk
  ignore_errors: True
  ansible.builtin.reboot:
    msg: ''
    connect_timeout: 1
    reboot_timeout: 1

# Turn everything back to normal
- name: Reapplying ssh config
  ansible.builtin.set_fact:
    ansible_port: '{{ edge_install_ansible_port }}'
    ansible_user: '{{ edge_install_ansible_user }}'

- name: Remove host from Controller's known hosts
  delegate_to: localhost
  connection: local
  ansible.builtin.known_hosts:
    name: '{{ ansible_host }}'
    state: absent

# Check if Reboot happened
- name: SSH Check
  ansible.builtin.wait_for_connection:
    timeout: 120
