---
- name: Ensuring traefik config folder exists
  ansible.builtin.file:
    path: '{{ traefik_config_folder }}'
    state: directory
    mode: 0755

- name: Ensuring traefik volumes folder exists
  ansible.builtin.file:
    path: '{{ traefik_volumes_folder }}'
    state: directory
    mode: 0555

- name: Creating traefik's acme.json file
  become: true
  ansible.builtin.file:
    path: '{{ (traefik_volumes_folder, "acme.json") | path_join }}'
    state: touch
    mode: 0600
    owner: 100000000
    group: 100000000
    
- name: Template Traefik's Static Config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: '{{ (traefik_config_folder, "traefik.yml") | path_join }}'
    mode: 0444
  register: traefik_static_config

#TODO: Consider using rsync
- name: Copy Traefik's dynamic file configs
  ansible.builtin.copy:
    src: configs/
    dest: '{{ (traefik_config_folder, "configs") | path_join }}'
    mode: 0444

- name: Template Traefik's Compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: '{{ (traefik_config_folder, "compose.yaml") | path_join }}'
    mode: 0444

- name: Adding services to firewalld
  become: true
  ansible.posix.firewalld:
    service: '{{ item }}'
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - https
    - http

- name: Start traefik
  community.docker.docker_compose_v2:
    project_src: '{{ traefik_config_folder }}'
    state: '{% if traefik_static_config is changed %}restarted{% else %}present{% endif %}'
