---
- name: Ensuring traefik config folder exists
  ansible.builtin.file:
    path: '{{ traefik_config_folder }}'
    state: directory
    mode: 0555

- name: Moving traefik configs
  become: true
  block:
    - name: Ensuring traefik dynamic config folder exists
      ansible.builtin.file:
        path: '{{ (traefik_config_folder, "configs") | path_join }}'
        state: directory
        mode: 0555
        owner: 100000
        group: 100000
    
    - name: Template Traefik's Static Config
      ansible.builtin.template:
        src: traefik.yml.j2
        dest: '{{ (traefik_config_folder, "traefik.yml") | path_join }}'
        mode: 0444
        owner: 100000
        group: 100000
      register: traefik_static_config
    
    #TODO: Consider using rsync
    - name: Copy Traefik's dynamic file configs
      ansible.builtin.copy:
        src: configs/
        dest: '{{ (traefik_config_folder, "configs") | path_join }}'
        mode: 0444
        owner: 100000
        group: 100000

- name: Create traefik network
  community.docker.docker_network:
    name: traefik
    driver: bridge
    internal: true
    state: present

- name: Create traefik-outside network
  community.docker.docker_network:
    name: traefik-outside
    driver: bridge
    internal: false
    state: present

- name: Create socket proxy container
  community.docker.docker_container:
    name: traefik-socket-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy
    keep_volumes: false
    userns_mode: host
    privileged: true
    restart_policy: unless-stopped
    mounts:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - name: traefik
        aliases:
          - 'socket-proxy'
    env:
      CONTAINERS: '1'

- name: Create reverse proxy container
  community.docker.docker_container:
    name: traefik
    image: traefik
    keep_volumes: false
    restart_policy: unless-stopped
    restart: '{{ traefik_static_config is changed }}'
    mounts:
      - type: bind
        source: '{{ (traefik_config_folder, "traefik.yml") | path_join }}'
        target: /etc/traefik/traefik.yml
        read_only: true
      - type: bind
        source: '{{ (traefik_config_folder, "configs") | path_join }}'
        target: /etc/traefik/configs
        read_only: true
    networks:
      - name: traefik
      - name: traefik-outside
      - name: '{{ reverse_proxy_network }}'
    published_ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8081:8081'
      - '127.0.0.1:8082:8082'
    labels:
      com.centurylinklabs.watchtower.depends-on: traefik-socket-proxy
