---
reverse_proxy_network: '{{ undef(hint="Reverse Proxy Docker network") }}'
authentik_role: '{{ undef(hint="Role of a server in a network (server|client)") }}'
rssbridge_config_folder: '{{ (container_config_folder | mandatory, "rssbridge") | path_join }}'
