---
piped_config_folder: '{{ (container_config_folder | mandatory, "piped") | path_join }}'
piped_data_folder: '{{ (container_volumes_folder | mandatory, "piped") | path_join }}'
piped_database_pass: '{{ undef(hint="Password for piped''s PostgreSQL instance") }}'
