---
zed_up_endpoint: '{{ undef(hint="UnifiedPush endpoint for ZED to send notifications to") }}'
smartd_up_endpoint: '{{ undef(hint="UnifiedPush endpoint for smartd to send notifications to") }}'
ddclient_hetzner_token: '{{ undef(hint="Token to give ddclient to update Hetzner''s DNS") }}'
