---
http:
  services:
    authentik:
      loadBalancer:
        servers:
          - url: 'http://{{ hostvars[authentik_server].wireguard_ip
                              | default(hostvars[authentik_server].wireguard_subnet | regex_replace("[0-9]{1,3}/[0-9]{1,2}$", "1")) }}:9000'
