---
- name: Ensuring data folder exists
  ansible.builtin.file:
    path: '{{ bitwarden_data_folder }}'
    state: directory
    mode: 0755

- name: Ensuring config folder exists
  ansible.builtin.file:
    path: '{{ bitwarden_config_folder }}'
    state: directory
    mode: 0700

- name: Creating Bitwarden volume folders
  become: true
  block:
    - name: Creating database folder
      ansible.builtin.file:
        path: '{{ (bitwarden_data_folder, "data") | path_join }}'
        state: directory
        mode: 0700
        owner: 100000999
        group: 100000999

    - name: Creating application folder
      ansible.builtin.file:
        path: '{{ (bitwarden_data_folder, "state") | path_join }}'
        state: directory
        mode: 0700
        owner: 100001000
        group: 100001000

    - name: Creating config file
      ansible.builtin.template:
        src: vaultwarden_ldap.toml.j2
        dest: '{{ (bitwarden_config_folder, "vaultwarden_ldap.toml") | path_join }}'
        mode: 0500
        owner: 100001000
        group: 100001000
      register: bitwarden_ldap_config_template

- name: Templating Vaultwarden's Compose
  ansible.builtin.template:
    src: compose.yml.j2
    dest: '{{ (bitwarden_config_folder, "compose.yml") | path_join }}'
    mode: 0700

- name: Start Bitwarden
  community.docker.docker_compose_v2:
    project_src: '{{ bitwarden_config_folder }}'
    state: '{% if bitwarden_ldap_config_template is changed %}restarted{% else %}present{% endif %}'

- name: Create DNS Records for bwarden.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: bwarden
    hetzner_dns_record_ipv4: '{{ public_ipv4 | default(omit) }}'
    hetzner_dns_record_ipv6: '{{ public_ipv6 | default(omit) }}'
