---
- name: Ensuring data folder exists
  ansible.builtin.file:
    path: '{{ bitwarden_data_folder }}'
    state: directory
    mode: 0755

- name: Ensuring config folder exists
  ansible.builtin.file:
    path: '{{ bitwarden_config_folder }}'
    state: directory
    mode: 0700

- name: Creating Bitwarden volume folders
  become: true
  block:
    - name: Creating database folder
      ansible.builtin.file:
        path: '{{ (bitwarden_data_folder, "data") | path_join }}'
        state: directory
        mode: 0700
        owner: 100000999
        group: 100000999

    - name: Creating application folder
      ansible.builtin.file:
        path: '{{ (bitwarden_data_folder, "state") | path_join }}'
        state: directory
        mode: 0700
        owner: 100001000
        group: 100001000

    - name: Creating config file
      ansible.builtin.template:
        src: vaultwarden_ldap.toml
        dest: '{{ (bitwarden_config_folder, "vaultwarden_ldap.toml") | path_join }}'
        mode: 0600
        owner: 100001000
        group: 100001000
      register: bitwarden_ldap_config_template

- name: Templating Vaultwarden's Compose
  ansible.builtin.template:
    src: compose.yml
    dest: '{{ (bitwarden_config_folder, "compose.yml") | path_join }}'
    mode: 0600

- name: Start Bitwarden
  community.docker.docker_compose_v2:
    project_src: '{{ bitwarden_config_folder }}'
  register: bitwarden_compose_started
  notify:
    - Add internal networks in firewalld

- name: Restart LDAP Inviter
  community.docker.docker_compose_v2:
    project_src: '{{ bitwarden_config_folder }}'
    state: restarted
    services:
      - ldap-inviter
  when: bitwarden_ldap_config_template is changed and (bitwarden_compose_started.actions | selectattr('id', 'contains', 'ldap-inviter') | length) <= 0

- name: Create DNS Records for bwarden.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: bwarden
