---
container_config_folder: '{{ undef(hint="Folder where the configuration files are kept") }}'
reverse_proxy_network: '{{ undef(hint="Name of the reverse proxy network") }}'
reverse_proxy_network_subnet: '{{ undef(hint="Subnet of the Reverse Proxy Network") }}'
reverse_proxy_network_gateway: '{{ reverse_proxy_network_subnet | regex_replace("[0-9]{1,3}/[0-9]{1,2}$", "1") }}'
