---
- collections:
    - ansible.builtin
  block:
    - name: Test ssh connection on configured port
      wait_for_connection:
        timeout: 10
      register: state_gathering_connection_test_result

    - name: Setting state variable
      set_fact:
        os_is_installed: "{{ state_gathering_connection_test_result is succeeded }}"
  ignore_errors: True
