---
reverse_proxy_network: '{{ undef(hint="Reverse Proxy Docker network") }}'
authentik_data_folder: '{{ (container_volumes_folder | mandatory, "authentik") | path_join }}'
authentik_secret_key: '{{ undef(hint="Secret key for authentik") }}'
authentik_database_pass: '{{ undef(hint="Password for authentik''s PostgreSQL instance") }}'
authentik_email:
  # SMTP Host Emails are sent to
  host: ''
  port: '587'
  # Optionally authenticate (don't add quotation marks to you password)
  username: ''
  password: ''
  # Use StartTLS
  use_tls: 'false'
  # Use SSL
  use_ssl: 'false'
  timeout: '30'
  # Email address authentik will send from, should have a correct @domain
  from: ''
