- become: true
  block:
    - name: Start and enable monthly scrub
      ansible.builtin.systemd_service:
        name: 'zfs-scrub-monthly@{{ zfs_pool_name }}.timer'
        enabled: true
        state: started
