---
- name: Ensuring container config folder exists
  ansible.builtin.file:
    path: '{{ rssbridge_config_folder }}'
    state: directory
    mode: 0744

- name: Configuring RSS-Bridge
  become: true
  block:
    - name: Ensuring rss-bridge config folder exists
      ansible.builtin.file:
        dest: '{{ (rssbridge_config_folder | mandatory, "config") | path_join }}'
        state: directory
        mode: 0744
        owner: 100001000
        group: 100001000

    - name: Creating config file
      ansible.builtin.template:
        src: rssbridge.php
        dest: '{{ (rssbridge_config_folder | mandatory, "config", "config.ini.php") | path_join }}'
        mode: 0700
        owner: 100001000
        group: 100001000
      register: rssbridge_config

- name: Templating compose file
  ansible.builtin.template:
    src: compose.yml
    dest: '{{ (rssbridge_config_folder | mandatory, "compose.yml") | path_join }}'
    mode: 0544

- name: Starting RSS-Bridge
  community.docker.docker_compose_v2:
    project_src: '{{ rssbridge_config_folder }}'
  register: rssbridge_compose_started

- name: Restartng RSS-Bridge
  community.docker.docker_compose_v2:
    project_src: '{{ rssbridge_config_folder }}'
    services:
      - server
    state: restarted
  when: rssbridge_config is changed and (rssbridge_compose_started.actions | selectattr('id', 'contains', 'server') | length) <= 0

- name: Create DNS Records for rss.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: rss
