---
- name: Rebooting to new snapshot and refreshing partition table
  become: true
  ansible.builtin.reboot:
    msg: Rebooting to new snapshot

- name: Waiting for server to come back up online after reboot
  ansible.builtin.wait_for_connection: {}

- become: true
  block:
    - name: Adding port to firewalld
      ansible.posix.firewalld:
        port: '{{ ansible_port }}/tcp'
        state: enabled
        permanent: true
        offline: true
      when: ansible_port != 22

    - name: Removing ssh from firewalld
      ansible.posix.firewalld:
        service: ssh
        state: disabled
        permanent: true
        offline: true
      when: ansible_port != 22

    - name: Enable firewalld
      ansible.builtin.systemd_service:
        name: firewalld.service
        enabled: true
        state: started

    - name: Restart docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        state: restarted
