---
- name: Ensuring config folder exists
  ansible.builtin.file:
    path: '{{ navidrome_config_folder }}'
    state: directory

- name: Ensuring data folder exists
  become: true
  ansible.builtin.file:
    path: '{{ navidrome_data_folder }}'
    state: directory
    mode: 0755
    owner: 100001000
    group: 100001000

- name: Templating Navidrome's Compose
  ansible.builtin.template:
    src: compose.yml
    dest: '{{ (navidrome_config_folder, "compose.yml") | path_join }}'

- name: Starting Navidrome
  community.docker.docker_compose_v2:
    project_src: '{{ navidrome_config_folder }}'

- name: Create DNS Records for music.magisystem.xyz
  ansible.builtin.import_role:
    name: hetzner/dns
  vars:
    hetzner_dns_record_prefix: music
    hetzner_dns_record_ipv4: '{{ public_ipv4 | default(omit) }}'
    hetzner_dns_record_ipv6: '{{ public_ipv6 | default(omit) }}'
