---
- name: Ensuring config folder exists
  ansible.builtin.file:
    path: '{{ container_config_folder }}'
    state: directory
    mode: 0755
    recurse: True

- name: Create services network
  containers.podman.podman_network:
    name: '{{ reverse_proxy_network }}'
    driver: bridge
    internal: True
    ipam_config:
      gateway: '{{ reverse_proxy_network_gateway }}'
      subnet: '{{ reverse_proxy_network_subnet }}'
    state: present
