---
- name: Get whether OS has been installed
  block:
    - name: Test ssh connection on configured port
      ansible.builtin.wait_for_connection:
        timeout: 10
      register: state_gathering_connection_test_result

    - name: Setting state variable
      ansible.builtin.set_fact:
        setup_completed: "{{ state_gathering_connection_test_result is succeeded }}"
  ignore_errors: true
