- become: true
  block:
    - name: Installing packages
      community.general.zypper:
        name:
          - hdparm
          - smartmontools
          - ddclient
          - docker

    - name: Install zfs
      block:
        - &install_zfs_packages
          name: Install zfs packages
          community.general.zypper:
            name:
              - zfs
              - zfs-kmp-default
              - zfs-ueficert
      rescue:
        # TODO: Do this only if there is no package that provides zfs
        - name: Add filesystems repo from Open Build Service
          community.general.zypper_repository:
            auto_import_keys: false
            repo: 'https://download.opensuse.org/repositories/filesystems/{{ ansible_facts.lsb.release }}/filesystems.repo'
        - *install_zfs_packages

    - name: Set ZED Email Address to UnifiedPush endpoint
      ansible.builtin.lineinfile:
        path: /etc/zfs/zed.d/zed.rc
        search_string: 'ZED_EMAIL_ADDR="'
        line: 'ZED_EMAIL_ADDR="{{ zed_up_endpoint }}"'

    - name: Point ZED to curl to send "emails"
      ansible.builtin.lineinfile:
        path: /etc/zfs/zed.d/zed.rc
        search_string: 'ZED_EMAIL_PROG="'
        line: 'ZED_EMAIL_PROG="curl"'

    - name: Set options to send ZED notifications with curl
      ansible.builtin.lineinfile:
        path: /etc/zfs/zed.d/zed.rc
        search_string: 'ZED_EMAIL_OPTS="'
        line: 'ZED_EMAIL_OPTS="-X POST --data @- ''@ADDRESS@''"'

    - name: Make Docker remap users by default
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/docker
        backrefs: true
        regexp: '^DOCKER_OPTS="(?!.*--userns-remap)(.*)"'
        line: 'DOCKER_OPTS="\1 --userns-remap default"'
      register: ayanami_setup_sysconfig_docker

    - name: Start and enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        state: '{% if ayanami_setup_sysconfig_docker is changed %}restarted{% else %}started{% endif %}'
